---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


   

   

    

## 網站資料爬取
```{r}
install.packages("rvest")
library(rvest)
PTT<-read_html("https://www.ptt.cc/bbs/Tech_Job/index.html")
btnURL<-PTT  %>% html_nodes("a[class ='btn wide']") %>% html_attr("href")
indexNum<-as.numeric(gsub("/bbs/Tech_Job/index|.html","",btnURL[2]))
totalPage<-NULL
for(i in (indexNum-4):(indexNum+1)){
   
    PTT=paste("https://www.ptt.cc/bbs/Tech_Job/index",i,".html",sep="")

    
Title <- read_html(PTT) %>% html_nodes(".title") %>% html_text() 

PushNum <- read_html(PTT) %>% html_nodes(".nrec") %>% html_text() 

Author <- read_html(PTT) %>% html_nodes(".author") %>% html_text() 

PTT_news <- data.frame(Title,PushNum,Author)


  
    totalPage<-rbind(totalPage,PTT_news)
}

  

View(totalPage)

    



```

## 爬蟲結果呈現
```{r}

knitr::kable(totalPage) 
```

## 解釋爬蟲結果 
```{r}
nrow(totalPage)


```

124篇

```{r}
table(totalPage$Author)
```
無發文最多之作者

124篇文章中有18篇被刪除

